-- generated by chatgpt.com 20241101
-- revised 20241121 to return default value if moniker is null
CREATE OR REPLACE FUNCTION engine.checkmemberflag(flag_name TEXT, membermoniker TEXT DEFAULT NULL)
RETURNS BOOLEAN AS $$
DECLARE
    map_value BOOLEAN;
BEGIN
    flag_name := lower(flag_name);

    -- If moniker is NULL, return the default value for the flag
    IF membermoniker IS NULL THEN
        SELECT f.defaultvalue
        INTO map_value
        FROM engine.member_flag f
        WHERE lower(f.name) = flag_name;

        -- If the flag doesn't exist, raise a notice and return NULL
        IF NOT FOUND THEN
            RAISE NOTICE 'flag_name not found %', flag_name;
            RETURN NULL;
        END IF;

        RETURN map_value; -- Return the default value directly
    END IF;

    membermoniker := lower(membermoniker);

    -- Check if flag_name exists in the member_flag table
    PERFORM 1 FROM engine.member_flag WHERE lower(name) = flag_name;

    -- If flag_name does not exist, return NULL
    IF NOT FOUND THEN
        RAISE NOTICE 'flag_name not found %', flag_name;
        RETURN NULL;
    END IF;

    -- Check if a moniker was provided and look for a matching entry in the member table
    PERFORM 1 FROM engine.member WHERE lower(engine.member.moniker) = membermoniker;

    -- If moniker does not exist in the member table, return NULL
    IF NOT FOUND THEN
        RAISE NOTICE 'moniker not found in member table: %', membermoniker;
        RETURN NULL;
    END IF;

    -- Look for a matching entry in the map table
    SELECT COALESCE(m.value, f.defaultvalue)
    INTO map_value
    FROM engine.member_flag f
    LEFT JOIN engine.map_member_flag m
        ON LOWER(m.moniker) = membermoniker AND LOWER(m.name) = LOWER(f.name)
    WHERE LOWER(f.name) = flag_name;

    -- If a value is found in the map, return it
    IF map_value IS NOT NULL THEN
        RETURN map_value;
    ELSE
        RETURN NULL;
    END IF;

END;
$$ LANGUAGE plpgsql;

grant EXECUTE on function engine.checkmemberflag to web, term, sysop, member;
