-- generated by chatgpt.com 2024-10-14
CREATE OR REPLACE FUNCTION engine.createrol(role_name TEXT)
RETURNS BOOLEAN AS
$$
DECLARE
    sql TEXT;
BEGIN
    -- Construct the SQL query to create the role
    sql := format('CREATE ROLE %I', role_name);

    -- Execute the constructed SQL query
    EXECUTE sql;

    -- Return true to indicate success
    RETURN TRUE;
EXCEPTION
    WHEN OTHERS THEN
        -- Handle any exceptions by raising the error
        RAISE EXCEPTION 'Error creating role: %', SQLERRM;
        RETURN FALSE;
END;
$$
LANGUAGE plpgsql;

grant execute on function engine.createrol to sysop;

-- Per-member psql access roles (ident auth, no password).
-- See handbook/specs/pg-ident-auth.md.

-- engine.createpgrole: derive 'l_' + sanitized(p_loginid),
-- collision-suffixed, CREATE ROLE ... LOGIN (no password),
-- GRANT member TO l_xxx, INSERT INTO engine.pgrole, return rolname.
-- Idempotent: if engine.pgrole already has a row for this member,
-- the existing rolname is returned (and osuser is updated if provided).
CREATE OR REPLACE FUNCTION engine.createpgrole(
  p_loginid TEXT,
  p_osuser  TEXT DEFAULT NULL
) RETURNS TEXT AS $$
DECLARE
  mmon     CITEXT;
  base     TEXT;
  rname    TEXT;
  n        INT := 0;
  existing TEXT;
BEGIN
  IF p_loginid IS NULL OR btrim(p_loginid) = '' THEN
    RAISE EXCEPTION 'createpgrole: loginid is required';
  END IF;

  -- Look up the member. engine.__member's natural key is moniker
  -- (citext); engine.pgrole.membermoniker references it.
  SELECT moniker INTO mmon FROM engine.__member WHERE loginid = p_loginid;
  IF mmon IS NULL THEN
    RAISE EXCEPTION 'createpgrole: no engine.__member row for loginid=%', p_loginid;
  END IF;

  -- Idempotency: if a row already exists for this member, return
  -- the existing rolname (and update osuser if a non-NULL one was
  -- provided).
  SELECT rolname INTO existing FROM engine.pgrole WHERE membermoniker = mmon;
  IF existing IS NOT NULL THEN
    IF p_osuser IS NOT NULL THEN
      UPDATE engine.pgrole SET osuser = p_osuser WHERE membermoniker = mmon;
    END IF;
    RETURN existing;
  END IF;

  -- No existing row. Derive a fresh rolname.
  base := 'l_' || lower(regexp_replace(p_loginid, '[^a-zA-Z0-9_]', '_', 'g'));
  rname := base;

  -- Collision loop against any existing pg_roles.rolname.
  WHILE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = rname) LOOP
    n := n + 1;
    rname := base || '_' || n;
  END LOOP;

  -- Create the LOGIN role. No PASSWORD clause: auth is by ident.
  EXECUTE format('CREATE ROLE %I LOGIN INHERIT', rname);

  -- Every approved member is a member of the 'member' group role.
  -- The 'member' group is created in pgrole.sql.
  EXECUTE format('GRANT member TO %I', rname);

  INSERT INTO engine.pgrole (membermoniker, rolname, osuser)
  VALUES (mmon, rname, p_osuser);

  RETURN rname;
END;
$$ LANGUAGE plpgsql;

grant execute on function engine.createpgrole(text, text) to sysop;

-- engine.deletepgrole: DROP ROLE IF EXISTS. The engine.pgrole row
-- goes away via the ON DELETE CASCADE from engine.__member, or we
-- can delete it explicitly here for safety.
CREATE OR REPLACE FUNCTION engine.deletepgrole(p_rolname NAME)
RETURNS VOID AS $$
BEGIN
  DELETE FROM engine.pgrole WHERE rolname = p_rolname;
  EXECUTE format('DROP ROLE IF EXISTS %I', p_rolname);
END;
$$ LANGUAGE plpgsql;

grant execute on function engine.deletepgrole(name) to sysop;

-- engine.syncpgrolegroups: keep a member's l_<loginid> role's group
-- memberships (sysop, term, web) in sync with the member's flags.
-- Called from console/member.py:edit() after flag changes.
CREATE OR REPLACE FUNCTION engine.syncpgrolegroups(p_membermoniker CITEXT)
RETURNS VOID AS $$
DECLARE
  rname     NAME;
  m_moniker TEXT;
  is_sysop  BOOLEAN;
  is_term   BOOLEAN;
  is_web    BOOLEAN;
BEGIN
  SELECT pr.rolname, mm.moniker
    INTO rname, m_moniker
    FROM engine.pgrole pr
    JOIN engine.__member mm ON mm.moniker = pr.membermoniker
   WHERE pr.membermoniker = p_membermoniker;

  IF rname IS NULL THEN
    RETURN;  -- no role yet; nothing to sync
  END IF;

  is_sysop := engine.checkmemberflag('sysop', m_moniker);
  is_term  := engine.checkmemberflag('term',  m_moniker);
  is_web   := engine.checkmemberflag('web',   m_moniker);

  IF is_sysop THEN
    IF NOT pg_has_role(rname, 'sysop', 'MEMBER') THEN
      EXECUTE format('GRANT sysop TO %I', rname);
    END IF;
  ELSE
    IF pg_has_role(rname, 'sysop', 'MEMBER') THEN
      EXECUTE format('REVOKE sysop FROM %I', rname);
    END IF;
  END IF;

  IF is_term THEN
    IF NOT pg_has_role(rname, 'term', 'MEMBER') THEN
      EXECUTE format('GRANT term TO %I', rname);
    END IF;
  ELSE
    IF pg_has_role(rname, 'term', 'MEMBER') THEN
      EXECUTE format('REVOKE term FROM %I', rname);
    END IF;
  END IF;

  IF is_web THEN
    IF NOT pg_has_role(rname, 'web', 'MEMBER') THEN
      EXECUTE format('GRANT web TO %I', rname);
    END IF;
  ELSE
    IF pg_has_role(rname, 'web', 'MEMBER') THEN
      EXECUTE format('REVOKE web FROM %I', rname);
    END IF;
  END IF;
END;
$$ LANGUAGE plpgsql;

grant execute on function engine.syncpgrolegroups(citext) to sysop;
