"""
Unit tests for ``bbsengine6.member.checkpassword`` and
``bbsengine6.member.rehashpassword`` — the local-verify and
opportunistic-rehash path that mirrors ``bbsengine6\\member\\lib\\
checkpassword`` and ``bbsengine6\\member\\lib\\rehashpassword`` on
the PHP side.

Pins (after the 2026-08-23 rewrite that removed the PG
``crypt(plaintext, password)`` round-trip):

  - checkpassword issues ONE SELECT for the stored hash. The SQL
    MUST NOT contain ``crypt(`` (that was the round-trip signal).
  - The verify runs locally: stdlib ``crypt(plaintext, stored)``
    first (handles ``$1$`` MD5-crypt + ``$5$``/``$6$`` SHA-crypt +
    ``$2[abxy]$`` bcrypt in one path), passlib ``bcrypt.verify``
    as a bcrypt-specific fallback.
  - On successful verify of a legacy hash, ``checkpassword``
    triggers ``rehashpassword`` to rewrite the column to a fresh
    ``$2b$06$...`` bcrypt value. Healthy hashes are not rewritten.
  - ``rehashpassword`` is a single UPDATE — no SELECT round-trip,
    no ``gen_salt`` in the wire SQL. The hash is produced locally by
    ``bbsengine6.util.encryptpassword`` (which delegates to
    ``bbsengine6.password.hash_password``).
  - CONN_POOL_PATTERN: cur=/conn=/pool=/args= are all honoured in
    priority order.

Why a separate file from ``test_member_audit_password_hash.py``:

  The audit-test file pins the per-auth diagnostic (``audit_-
  password_hash`` is invoked on the same cursor, warning levels
  fire on legacy hashes). This file pins the verify + rehash
  contract. The two concerns diverge enough that combining them
  would obscure each test's intent. Both files import the
  ``bbsengine6.member.lib`` module — they are siblings, not a
  hierarchy.
"""

import contextlib
import warnings
from unittest.mock import Mock

import pytest

from bbsengine6 import database, member as libmember


pytestmark = pytest.mark.unit


# ---------------------------------------------------------------------------
# Real-world hashes for the verify path
# ---------------------------------------------------------------------------


# Real bcrypt hash for plaintext "12345" generated via passlib with a
# deterministic salt so the test value is stable across runs. The
# salt is 22 base64-ish chars; the cost is 4 for fast test execution.
try:
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        from passlib.hash import bcrypt as _pl_bcrypt

    _HEALTHY_BCRYPT_HASH = _pl_bcrypt.using(
        rounds=4, salt="abcdefghijklmnopqrstuv"
    ).hash("12345")
except ImportError:  # pragma: no cover
    pytest.skip("passlib not installed; cannot exercise verify path", allow_module_level=False)
    _HEALTHY_BCRYPT_HASH = "$2b$04$" + "Z" * 22 + "." * 31


# Real $1$ MD5-crypt hash for plaintext "12345" generated by stdlib
# crypt with a deterministic salt. The resulting hash is verifiable
# by stdlib crypt() (this is the whole point of the fallback path).
import crypt as _crypt
_LEGACY_MD5_HASH = _crypt.crypt("12345", "$1$abcdefghijkl")


# ---------------------------------------------------------------------------
# Spy fixtures
# ---------------------------------------------------------------------------


class _SpyCursor:
    """Cursor stand-in for the local-verify + rehash test path.

    Behaves like a real psycopg cursor for the small subset that
    ``checkpassword`` and ``rehashpassword`` use:

      - ``execute(query, params)`` records the call. The first
        SELECT (row fetch) sets ``_row`` so ``fetchone()`` returns
        it on the next call. Subsequent UPDATEs (rehash) just
        increment ``_update_count`` and set ``rowcount`` to 1.
      - ``fetchone()`` returns the stored password row once, then
        None on the second call (mimics PG's read-once cursor
        semantics for the SELECT case).
      - ``rowcount`` reflects the last UPDATE (1 for success,
        0 for no row matched).

    Mirrors the ``_SpyCursor`` pattern in
    ``test_console_member_add_edit.py`` and
    ``test_member_audit_password_hash.py``.
    """

    def __init__(self, stored_password=None, rowcount=1, return_row=True):
        self._row = (
            {"password": stored_password} if return_row else None
        )
        self._rowcount = rowcount
        self._update_count = 0
        self._select_count = 0
        self.calls = []  # list of (query, params)

    def __enter__(self):
        return self

    def __exit__(self, *a):
        return False

    def execute(self, query, params=None):
        self.calls.append((query, params))
        rendered = (
            query.as_string(None)
            if hasattr(query, "as_string")
            else str(query)
        ).lower()
        if rendered.lstrip().startswith("select "):
            self._select_count += 1
        elif rendered.lstrip().startswith("update "):
            self._update_count += 1

    def fetchone(self):
        # The SELECT in checkpassword fetches exactly one row; the
        # rehash UPDATE never calls fetchone. So fetchone is called
        # at most once and always returns the row we stashed.
        return self._row

    @property
    def rowcount(self):
        return self._rowcount

    @rowcount.setter
    def rowcount(self, value):
        self._rowcount = value


class _SpyConn:
    """Connection stand-in that emits a single ``_SpyCursor``."""

    def __init__(self, cursor):
        self._cursor = cursor
        self.committed = False
        self.rolled_back = False

    def cursor(self, **kw):
        return self._cursor

    def commit(self):
        self.committed = True

    def rollback(self):
        self.rolled_back = False

    @property
    def autocommit(self):
        return False

    @autocommit.setter
    def autocommit(self, value):
        pass

    @property
    def pgconn(self):
        m = Mock()
        m.transaction_status = 0
        return m


def _make_args(**overrides):
    defaults = dict(
        debug=False,
        databasename="zoid6test",
        databasehost="localhost",
        databaseport=5432,
        databaseschema="engine",
    )
    defaults.update(overrides)
    return Mock(**defaults)


@pytest.fixture
def args():
    return _make_args()


@pytest.fixture
def echo_calls(monkeypatch):
    """Capture every ``io.echo(..., level=...)`` call."""
    from bbsengine6 import io

    captured = []
    real_echo = io.echo

    def _spy(text, *a, **kw):
        level = kw.get("level")
        if level is not None:
            captured.append((level, text))
        return real_echo(text, *a, **kw)

    monkeypatch.setattr(io, "echo", _spy)
    monkeypatch.setattr(libmember.io, "echo", _spy)
    return captured


def _patch_connect(monkeypatch, cursor):
    """Patch ``database.connect`` to yield a ``_SpyConn(cursor)``."""

    @contextlib.contextmanager
    def _cm(*a, **kw):
        conn = _SpyConn(cursor)
        try:
            yield conn
        except BaseException:
            conn.rollback()
            raise

    monkeypatch.setattr(database, "connect", _cm)


# ---------------------------------------------------------------------------
# checkpassword - local-verify contract
# ---------------------------------------------------------------------------


def test_checkpassword_no_pg_crypt_round_trip(args, monkeypatch, echo_calls):
    """checkpassword must NOT issue a SELECT containing ``crypt(``.

    The pre-2026-08-23 code emitted
    ``select 1 from ... where password=crypt(%s, password)``.
    After the local-verify rewrite the verify runs entirely in
    Python; the only SELECT is the row fetch for the stored hash.
    """
    cursor = _SpyCursor(stored_password=_HEALTHY_BCRYPT_HASH)
    _patch_connect(monkeypatch, cursor)

    libmember.checkpassword(args, "12345", membermoniker="jam", pool=Mock())

    for query, _params in cursor.calls:
        rendered = (
            query.as_string(None)
            if hasattr(query, "as_string")
            else str(query)
        ).lower()
        assert "crypt(" not in rendered, (
            f"checkpassword must not contain crypt() in SQL (PG round-trip "
            f"removed); got: {rendered!r}"
        )


def test_checkpassword_issues_exactly_two_selects_no_updates_on_healthy(
    args, monkeypatch, echo_calls
):
    """One SELECT for the row fetch. The audit runs on the same cursor
    and issues its own SELECT - that is one additional SELECT, so the
    total is 2 SELECTs and 0 UPDATEs on a healthy (no rehash) path.
    """
    cursor = _SpyCursor(stored_password=_HEALTHY_BCRYPT_HASH)
    _patch_connect(monkeypatch, cursor)

    result = libmember.checkpassword(
        args, "12345", membermoniker="jam", pool=Mock()
    )

    assert result is True
    assert cursor._select_count == 2, (
        f"checkpassword on a healthy row must issue 2 SELECTs (row + audit); "
        f"got {cursor._select_count}"
    )
    assert cursor._update_count == 0, (
        f"healthy row must not trigger a rehash UPDATE; "
        f"got {cursor._update_count} UPDATEs"
    )


def test_checkpassword_verifies_healthy_bcrypt_locally(
    args, monkeypatch, echo_calls
):
    """Correct plaintext against a healthy ``$2b$06$...`` row returns True."""
    cursor = _SpyCursor(stored_password=_HEALTHY_BCRYPT_HASH)
    _patch_connect(monkeypatch, cursor)

    result = libmember.checkpassword(
        args, "12345", membermoniker="jam", pool=Mock()
    )

    assert result is True, (
        f"checkpassword must verify a correct bcrypt plaintext locally; "
        f"got {result!r}"
    )


def test_checkpassword_rejects_wrong_plaintext(args, monkeypatch, echo_calls):
    """Wrong plaintext returns False. No rehash fires (the stored hash
    is not the thing that's wrong)."""
    cursor = _SpyCursor(stored_password=_HEALTHY_BCRYPT_HASH)
    _patch_connect(monkeypatch, cursor)

    result = libmember.checkpassword(
        args, "wrong-password", membermoniker="jam", pool=Mock()
    )

    assert result is False, (
        f"checkpassword must reject a wrong plaintext; got {result!r}"
    )
    assert cursor._update_count == 0, (
        f"verify-failed path must not trigger a rehash UPDATE; "
        f"got {cursor._update_count} UPDATEs"
    )


def test_checkpassword_returns_false_for_missing_row(
    args, monkeypatch, echo_calls
):
    """A moniker not in ``engine.__member`` returns False (no raise)."""
    cursor = _SpyCursor(stored_password=None, return_row=False)
    _patch_connect(monkeypatch, cursor)

    result = libmember.checkpassword(
        args, "anything", membermoniker="nobody", pool=Mock()
    )

    assert result is False, (
        f"checkpassword on a missing row must return False (not None, "
        f"not raise); got {result!r}"
    )


def test_checkpassword_tolerates_malformed_stored_hash(
    args, monkeypatch, echo_calls
):
    """A garbage stored value (e.g. truncated hash from a botched
    migration) must NOT raise. ``_verify_any`` returns False on
    any malformed input so checkpassword can return False cleanly.
    """
    cursor = _SpyCursor(stored_password="garbage-not-a-hash")
    _patch_connect(monkeypatch, cursor)

    result = libmember.checkpassword(
        args, "12345", membermoniker="jam", pool=Mock()
    )

    assert result is False, (
        f"checkpassword on a malformed stored hash must return False "
        f"(never raise); got {result!r}"
    )


def test_checkpassword_opportunistic_rehash_on_legacy_hash(
    args, monkeypatch, echo_calls
):
    """The 2026-08-22 incident: stored hash is ``$1$`` MD5-crypt.
    Correct plaintext must verify AND trigger ``rehashpassword`` to
    rewrite the column to a fresh ``$2b$06$...`` bcrypt value. The
    row-fetch SELECT is followed by ONE UPDATE on the same cursor.
    """
    cursor = _SpyCursor(stored_password=_LEGACY_MD5_HASH)
    _patch_connect(monkeypatch, cursor)

    result = libmember.checkpassword(
        args, "12345", membermoniker="jam", pool=Mock()
    )

    assert result is True, (
        f"checkpassword must verify a correct plaintext against a "
        f"legacy $1$ MD5-crypt hash (stdlib crypt fallback path); "
        f"got {result!r}"
    )
    assert cursor._update_count == 1, (
        f"successful verify of a legacy hash must trigger exactly one "
        f"rehash UPDATE; got {cursor._update_count} UPDATEs"
    )


def test_checkpassword_rehash_update_sql_has_no_crypt_or_gen_salt(
    args, monkeypatch, echo_calls
):
    """The rehash UPDATE must NOT contain ``crypt(`` or ``gen_salt``.
    The hash is pre-computed by ``bbsengine6.util.encryptpassword``;
    the SQL is just ``set password=$1 where moniker=$2``.
    """
    cursor = _SpyCursor(stored_password=_LEGACY_MD5_HASH)
    _patch_connect(monkeypatch, cursor)

    libmember.checkpassword(args, "12345", membermoniker="jam", pool=Mock())

    update_calls = [
        (q, p) for q, p in cursor.calls
        if _render_query(q).lstrip().startswith("update ")
    ]
    assert len(update_calls) == 1, (
        f"expected exactly one UPDATE (the rehash); got {len(update_calls)}"
    )
    assert "crypt(" not in _render_query(update_calls[0][0])
    assert "gen_salt" not in _render_query(update_calls[0][0])


def _render_query(q):
    """Render a psycopg Composed/SQL object to its SQL text.

    str(Composed) returns a Python repr, not SQL. as_string(None)
    produces the actual SQL that would be sent to PG.
    """
    return (q.as_string(None) if hasattr(q, "as_string") else str(q)).lower()


def test_checkpassword_conn_pool_pattern_uses_existing_cursor(args, monkeypatch):
    """``cur=`` keyword bypasses connect entirely. ``database.connect``
    must NOT be invoked when the caller supplies a cursor."""
    cursor = _SpyCursor(stored_password=_HEALTHY_BCRYPT_HASH)

    connect_called = []

    def _fail_connect(*a, **kw):
        connect_called.append((a, kw))
        raise RuntimeError(
            "database.connect must not be called when cur= is supplied"
        )

    monkeypatch.setattr(database, "connect", _fail_connect)

    result = libmember.checkpassword(
        args, "12345", membermoniker="jam", cur=cursor
    )

    assert result is True
    assert connect_called == [], (
        "cur= must short-circuit the connect path; database.connect "
        "was called"
    )
    assert cursor._select_count == 2
    assert cursor._update_count == 0


def test_checkpassword_conn_pool_pattern_uses_existing_conn(args, monkeypatch):
    """``conn=`` reuses the caller's connection. ``database.connect``
    must NOT be invoked; the spy conn is used directly."""
    cursor = _SpyCursor(stored_password=_HEALTHY_BCRYPT_HASH)
    conn = _SpyConn(cursor)

    connect_called = []
    monkeypatch.setattr(
        database, "connect",
        lambda *a, **kw: connect_called.append((a, kw)) or (_ for _ in ()).throw(
            RuntimeError("connect must not be called when conn= is supplied")
        ),
    )

    result = libmember.checkpassword(
        args, "12345", membermoniker="jam", conn=conn
    )

    assert result is True
    assert connect_called == []


def test_checkpassword_conn_pool_pattern_uses_existing_pool(args, monkeypatch):
    """``pool=`` borrows a connection from the caller's pool.
    ``database.connect(args, pool=pool)`` is invoked; ``database.
    getpool(args)`` is NOT."""
    cursor = _SpyCursor(stored_password=_HEALTHY_BCRYPT_HASH)
    pool = Mock()
    _patch_connect(monkeypatch, cursor)

    getpool_called = []
    monkeypatch.setattr(
        database, "getpool",
        lambda *a, **kw: getpool_called.append((a, kw)) or Mock(),
    )

    result = libmember.checkpassword(
        args, "12345", membermoniker="jam", pool=pool
    )

    assert result is True
    assert getpool_called == [], (
        "pool= must bypass database.getpool; getpool was called"
    )


def test_checkpassword_conn_pool_pattern_falls_through_to_getpool(
    args, monkeypatch, echo_calls
):
    """No cur/conn/pool supplied but args is not None: ``database.
    getpool(args)`` is invoked to build/cache the pool, then connect."""
    cursor = _SpyCursor(stored_password=_HEALTHY_BCRYPT_HASH)
    _patch_connect(monkeypatch, cursor)

    pool = Mock()
    monkeypatch.setattr(database, "getpool", lambda *a, **kw: pool)

    result = libmember.checkpassword(
        args, "12345", membermoniker="jam"
    )

    assert result is True


def test_checkpassword_returns_none_when_no_pool_and_no_args(args, monkeypatch):
    """No cur/conn/pool and no args: ``checkpassword`` returns None
    and logs a level=error diagnostic. No NPE, no infinite loop."""
    monkeypatch.setattr(database, "connect", Mock())

    result = libmember.checkpassword("not-an-args-object", "12345", membermoniker="jam")

    assert result is None, (
        f"checkpassword with no cur/conn/pool/args must return None; "
        f"got {result!r}"
    )


# ---------------------------------------------------------------------------
# rehashpassword - standalone helper
# ---------------------------------------------------------------------------


def test_rehashpassword_issues_one_update(args, monkeypatch, echo_calls):
    """``rehashpassword`` is a single UPDATE - no SELECT round-trip,
    no ``gen_salt``. The hash is produced locally by
    ``bbsengine6.util.encryptpassword``."""
    cursor = _SpyCursor(stored_password=None)
    _patch_connect(monkeypatch, cursor)

    result = libmember.rehashpassword(
        args, "jam", "12345", pool=Mock()
    )

    assert result is True, (
        f"rehashpassword on a matching moniker must return True; "
        f"got {result!r}"
    )
    assert cursor._update_count == 1, (
        f"rehashpassword must issue exactly one UPDATE; "
        f"got {cursor._update_count}"
    )
    assert cursor._select_count == 0, (
        f"rehashpassword must NOT issue any SELECT (no round-trip); "
        f"got {cursor._select_count}"
    )


def test_rehashpassword_update_sql_has_no_crypt_or_gen_salt(
    args, monkeypatch, echo_calls
):
    """Standalone rehashpath SQL mirrors the PHP-side UPDATE: just
    ``set password=$1 where moniker=$2``. No ``crypt(`` or
    ``gen_salt`` in the wire SQL."""
    cursor = _SpyCursor(stored_password=None)
    _patch_connect(monkeypatch, cursor)

    libmember.rehashpassword(args, "jam", "12345", pool=Mock())

    update_calls = [
        (q, p) for q, p in cursor.calls
        if _render_query(q).lstrip().startswith("update ")
    ]
    assert len(update_calls) == 1
    assert "crypt(" not in _render_query(update_calls[0][0])
    assert "gen_salt" not in _render_query(update_calls[0][0])


def test_rehashpassword_returns_false_on_zero_rowcount(
    args, monkeypatch, echo_calls
):
    """If the UPDATE matches zero rows (moniker doesn't exist),
    ``rehashpassword`` returns False (not None - we distinguish
    'no row' from 'connection failure')."""
    cursor = _SpyCursor(stored_password=None, rowcount=0)
    _patch_connect(monkeypatch, cursor)

    result = libmember.rehashpassword(
        args, "ghost", "12345", pool=Mock()
    )

    assert result is False, (
        f"rehashpassword on a missing moniker must return False; "
        f"got {result!r}"
    )


def test_rehashpassword_returns_none_on_connect_failure(
    args, monkeypatch, echo_calls
):
    """If the connection fails, ``rehashpassword`` returns None and
    logs a traceback. Caller can distinguish 'no row' (False) from
    'connection failure' (None) without parsing exception messages."""
    def _broken_connect(*a, **kw):
        raise RuntimeError("simulated PG outage")

    monkeypatch.setattr(database, "connect", _broken_connect)

    result = libmember.rehashpassword(args, "jam", "12345", pool=Mock())

    assert result is None, (
        f"rehashpassword on connect failure must return None; "
        f"got {result!r}"
    )


def test_rehashpassword_uses_existing_cursor(args, monkeypatch):
    """``cur=`` short-circuits connect."""
    cursor = _SpyCursor(stored_password=None)

    connect_called = []
    monkeypatch.setattr(
        database, "connect",
        lambda *a, **kw: connect_called.append((a, kw)) or (_ for _ in ()).throw(
            RuntimeError("connect must not be called when cur= is supplied")
        ),
    )

    result = libmember.rehashpassword(args, "jam", "12345", cur=cursor)

    assert result is True
    assert connect_called == []
    assert cursor._update_count == 1
