# message_delivery/__init__.py
# Public API for bbsengine6 message delivery system
# Combines notify module (Phase 1F rename) with delivery handlers (Phase 1D)

import warnings

from .lib import (
    _types,
    _types_lock,
    NotificationUrgency,
    Notification,
    NotificationTamperError,
    UserNotificationQueue,
    send,
    count,
    get_notifications,
    get_queue,
    get_urgent,
    mark_read,
    mark_delivered,
    expunge,
    register_type,
    get_types,
    create_group,
    add_to_group,
    get_group_members,
    remove_from_group,
    block,
    unblock,
    is_blocked,
    get_blocked,
    set_rate_limit,
    _validate_moniker,
    _validate_type_name,
    _validate_template,
    _validate_template_vars,
    _render_template,
    is_enabled,
    enable,
    disable,
)

from .tui import run, run_until_quit

from ..message_delivery_handlers import (
    DeliveryHandler,
    EmailDeliveryHandler,
    SMSDeliveryHandler,
    InMemoryQueueHandler,
    DeliveryManager,
    get_delivery_manager,
    subscribe_channel,
    publish_to_channel,
    register_handler,
    is_enabled as _delivery_is_enabled,
    enable as _delivery_enable,
    disable as _delivery_disable,
)

__all__ = [
    "_types",
    "_types_lock",
    "NotificationUrgency",
    "Notification",
    "NotificationTamperError",
    "UserNotificationQueue",
    "send",
    "count",
    "get_notifications",
    "get_queue",
    "get_urgent",
    "mark_read",
    "mark_delivered",
    "expunge",
    "register_type",
    "get_types",
    "create_group",
    "add_to_group",
    "get_group_members",
    "remove_from_group",
    "block",
    "unblock",
    "is_blocked",
    "get_blocked",
    "set_rate_limit",
    "_validate_moniker",
    "_validate_type_name",
    "_validate_template",
    "_validate_template_vars",
    "_render_template",
    "run",
    "run_until_quit",
    "is_enabled",
    "enable",
    "disable",
    "DeliveryHandler",
    "EmailDeliveryHandler", 
    "SMSDeliveryHandler",
    "InMemoryQueueHandler",
    "DeliveryManager",
    "get_delivery_manager",
    "subscribe_channel",
    "publish_to_channel",
    "register_handler",
]
