# notify/__init__.py
# BACKWARD COMPATIBILITY ALIAS
# This module is deprecated. Use bbsengine6.message_delivery instead.
#
# This module re-exports everything from bbsengine6.message_delivery
# to maintain backward compatibility with existing code.

import warnings

warnings.warn(
    "bbsengine6.notify is deprecated. Use bbsengine6.message_delivery instead.",
    DeprecationWarning,
    stacklevel=2
)

from ..message_delivery import (
    _types,
    _types_lock,
    NotificationUrgency,
    Notification,
    NotificationTamperError,
    UserNotificationQueue,
    send,
    count,
    get_notifications,
    get_queue,
    get_urgent,
    mark_read,
    mark_delivered,
    expunge,
    register_type,
    get_types,
    create_group,
    add_to_group,
    get_group_members,
    remove_from_group,
    block,
    unblock,
    is_blocked,
    get_blocked,
    set_rate_limit,
    _validate_moniker,
    _validate_type_name,
    _validate_template,
    _validate_template_vars,
    _render_template,
    is_enabled,
    enable,
    disable,
    run,
    run_until_quit,
    DeliveryHandler,
    EmailDeliveryHandler,
    SMSDeliveryHandler,
    InMemoryQueueHandler,
    DeliveryManager,
    get_delivery_manager,
    subscribe_channel,
    publish_to_channel,
    register_handler,
)

__all__ = [
    "_types",
    "_types_lock",
    "NotificationUrgency",
    "Notification",
    "NotificationTamperError",
    "UserNotificationQueue",
    "send",
    "count",
    "get_notifications",
    "get_queue",
    "get_urgent",
    "mark_read",
    "mark_delivered",
    "expunge",
    "register_type",
    "get_types",
    "create_group",
    "add_to_group",
    "get_group_members",
    "remove_from_group",
    "block",
    "unblock",
    "is_blocked",
    "get_blocked",
    "set_rate_limit",
    "_validate_moniker",
    "_validate_type_name",
    "_validate_template",
    "_validate_template_vars",
    "_render_template",
    "run",
    "run_until_quit",
    "is_enabled",
    "enable",
    "disable",
    "DeliveryHandler",
    "EmailDeliveryHandler",
    "SMSDeliveryHandler",
    "InMemoryQueueHandler",
    "DeliveryManager",
    "get_delivery_manager",
    "subscribe_channel",
    "publish_to_channel",
    "register_handler",
]
