# notify/__init__.py
# Public API for bbsengine6 notification system

from .lib import (
    _types,
    _types_lock,
    NotificationUrgency,
    Notification,
    NotificationTamperError,
    UserNotificationQueue,
    send,
    count,
    get_notifications,
    get_queue,
    get_urgent,
    mark_read,
    mark_delivered,
    expunge,
    register_type,
    get_types,
    create_group,
    add_to_group,
    get_group_members,
    remove_from_group,
    block,
    unblock,
    is_blocked,
    get_blocked,
    set_rate_limit,
    _validate_moniker,
    _validate_type_name,
    _validate_template,
    _validate_template_vars,
    _render_template,
)

from .tui import run, run_until_quit

__all__ = [
    "_types",
    "_types_lock",
    "NotificationUrgency",
    "Notification",
    "NotificationTamperError",
    "UserNotificationQueue",
    "send",
    "count",
    "get_notifications",
    "get_queue",
    "get_urgent",
    "mark_read",
    "mark_delivered",
    "expunge",
    "register_type",
    "get_types",
    "create_group",
    "add_to_group",
    "get_group_members",
    "remove_from_group",
    "block",
    "unblock",
    "is_blocked",
    "get_blocked",
    "set_rate_limit",
    "_validate_moniker",
    "_validate_type_name",
    "_validate_template",
    "_validate_template_vars",
    "_render_template",
    "run",
    "run_until_quit",
]
