[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bbsengine6"
dynamic = ["version"]
requires-python = ">=3.9,<3.13"
license = "GPL-2.0-or-later"
authors = [
    { name = "zoidtechnologies.com", email = "bbsengine6@projects.zoidtechnologies.com" },
]
urls = { Homepage = "https://bbsengine.org/" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Communications :: BBS",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Terminals",
]
dependencies = [
    # "wcwidth",
    "argcomplete",
    "psycopg[binary]",
    "psycopg2-binary",
    "psycopg-pool",
    "python-dateutil",
    "getdate-next",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["bbsengine6*"]

[tool.setuptools.dynamic]
version = { attr = "bbsengine6._version.__version__" }
