<?php

namespace bbsengine6\util
{
    /**
     * put $message into a log at the given priority
     *
     * @since 20080105
     * @since 20221116
     * @param string
     * @param enum
     */
    function logentry(string $message, int $priority=PEAR_LOG_DEBUG)
    {

      if (defined("LOGENTRYPREFIX") === false)
      {
        define("LOGENTRYPREFIX", "bbsengine6");
      }

      $logger = \Log::factory("syslog", "", LOGENTRYPREFIX, [], PEAR_LOG_DEBUG);
    //  $logger->log("bbsengine5.logentry.100: _SERVER=".var_export($_SERVER, true), $priority);
      $ip = getremoteaddr(); // $_SERVER["REMOTE_ADDR"];

      $logger->log($message, $priority);
      return;
    }

    /**
     * calls json_encode() with default parameters
     *
     * @since 20140730
     * @since 20230329 copied from bbsengine5.php
     */
    function encodejson($data)
    {
     // @see http://us3.php.net/manual/en/json.constants.php
     return json_encode($data); // , JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_NUMERIC_CHECK); // JSON_UNESCAPED_UNICODE in 5.4+
    }

    /**
     * decodes given json data into a dictionary (associative array)
     *
     * @since 20140730
     * @since 20230329 copied from bbsengine5.php
     */
    function decodejson($data)
    {
     if (is_string($data) === false)
     {
      logentry("decodejson.100: data=".var_export($data, true));
      return;
     }
     return json_decode($data, true);
    }

    /**
     * @since 20180804
     * @since 20240807 ported to bbsengine6
     * @since 20240914 moved to \bbsengine6\util
     * @param mixed field
     * @param string label
     * @param boolean default
     * @return boolean
     */
    function toboolean($value, $label="label", $default=false)
    {
      if (is_null($value) === true)
      {
        return $default;
      }

      if (is_bool($value) === true)
      {
        return $value;
      }

      if ($value === "t" || $value == 1 || $value == "true")
      {
        return true;
      }

      if ($value === "f" || $value == 0 || $value == "false")
      {
        return false;
      }

    //  logentry("toboolean.170: returning default of ".var_export($default, true)." for ".var_export($label, true));
      return $default;
    }

  // @since 20240921 generated by chatgpt.com
  function ltreeToPath(string $ltree) {
    // Split the ltree path by periods
    $labels = explode('.', $ltree);

    // Remove the reference to 'top'
    if ($labels[0] === 'top') {
      array_shift($labels);
    }

    // Join the remaining labels into a filesystem path with slashes
    return implode('/', $labels);
  }

  // @since 20240921 generated by chatgpt.com
  function chopLastElement($ltree) {
    $labels = explode('.', $ltree);
    logentry("engine.util.chopLastElement.100: ltree=".var_export($ltree, true)." labels=".var_export($labels, true));
/*
    // If there's only one element, return the original ltree
    if (count($labels) <= 1) {
        return $ltree;
    }
*/
    array_pop($labels);
    return implode('.', $labels);
  }

  // @since 20241030
  // @since 20251128 security: added IP validation to prevent spoofing
  function getremoteaddr(bool $allowForwarded = false): ?string
  {
    $result = null;

    if ($allowForwarded)
    {
      if (!empty($_SERVER['HTTP_CLIENT_IP']))
      {
        $result = trim($_SERVER['HTTP_CLIENT_IP']);
      }
      elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR']))
      {
        $ipList = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);
        $result = trim($ipList[0]);
      }
    }

    if ($result === null)
    {
      $result = $_SERVER["REMOTE_ADDR"] ?? null;
    }

    if ($result !== null && filter_var($result, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) === false)
    {
      $result = $_SERVER["REMOTE_ADDR"] ?? null;
    }

    return $result;
  }

  function getremoteaddr_allowforwarded(): ?string
  {
    return getremoteaddr(true);
  }

  function actionlog(string $action, string $note=null, string $moniker=null)
  {
    if ($moniker === null)
    {
      $moniker = \bbsengine6\member\lib\getcurrentmoniker();
    }
    $pdo = \bbsengine6\database\connect(\config\SYSTEMDSN);
    $data = ["moniker" => $moniker, "action" => $action, "actiondate" => "now()","remoteaddr" => getremoteaddr(), "note" => $note];
    \bbsengine6\database\insert($pdo, "engine.__actionlog", $data, $returnid=false, $mogrify=true);

    return true;
  }

  const CSRF_TOKEN_NAME = 'csrf_token';
  const CSRF_TOKEN_LENGTH = 32;

  function csrfGenerateToken(): string
  {
    if (session_status() === PHP_SESSION_NONE)
    {
      session_start();
    }

    if (!isset($_SESSION[CSRF_TOKEN_NAME]))
    {
      $_SESSION[CSRF_TOKEN_NAME] = bin2hex(random_bytes(CSRF_TOKEN_LENGTH));
    }

    return $_SESSION[CSRF_TOKEN_NAME];
  }

  function csrfGetToken(): string
  {
    return csrfGenerateToken();
  }

  function csrfValidateToken(string $token): bool
  {
    if (session_status() === PHP_SESSION_NONE)
    {
      session_start();
    }

    if (!isset($_SESSION[CSRF_TOKEN_NAME]))
    {
      return false;
    }

    $storedToken = $_SESSION[CSRF_TOKEN_NAME];
    return hash_equals($storedToken, $token);
  }

  function csrfTokenField(): string
  {
    $token = csrfGetToken();
    return '<input type="hidden" name="' . CSRF_TOKEN_NAME . '" value="' . htmlspecialchars($token, ENT_QUOTES, 'UTF-8') . '">';
  }

  function csrfCheckRequest(): bool
  {
    if ($_SERVER['REQUEST_METHOD'] === 'POST')
    {
      $token = $_POST[CSRF_TOKEN_NAME] ?? $_POST['csrf_token'] ?? null;
      if ($token === null)
      {
        logentry("csrfCheckRequest.100: missing token in POST");
        return false;
      }
      return csrfValidateToken($token);
    }
    elseif ($_SERVER['REQUEST_METHOD'] === 'GET')
    {
      $token = $_GET[CSRF_TOKEN_NAME] ?? $_GET['csrf_token'] ?? null;
      if ($token === null)
      {
        return true;
      }
      return csrfValidateToken($token);
    }
    return true;
  }

  function isDebugMode(): bool
  {
    return getenv('DEBUG') === '1' || ($_SERVER['DEBUG'] ?? '0') === '1';
  }

  function format_exception(\Throwable $e): string
  {
    $trace = $e->getTraceAsString();
    $prev = $e->getPrevious();
    while ($prev !== null) {
      $trace .= "\n\nPrevious: " . $prev->getMessage() . "\n" . $prev->getTraceAsString();
      $prev = $prev->getPrevious();
    }
    return $e->getMessage() . "\n" . $trace;
  }

  function echo_traceback(string $message, bool $showToUser = null): void
  {
    if ($showToUser === null) {
      $showToUser = isDebugMode();
    }

    $e = error_get_last();
    $formatted = '';
    if ($e !== null) {
      $formatted = $e['message'] . " in " . $e['file'] . " line " . $e['line'];
    }

    logentry("ERROR: " . $message . " | Trace: " . $formatted);

    if ($showToUser) {
      echo "<pre style='background:#fee;border:1px solid red;padding:10px;'>Error: " . htmlspecialchars($message, ENT_QUOTES, 'UTF-8') . "\n" . htmlspecialchars($formatted, ENT_QUOTES, 'UTF-8') . "</pre>";
    } else {
      echo "An error occurred. Please try again later.";
    }
  }

/**
 * safe_path — robust, flexible filesystem path constructor
 *
 * Intended for trusted/internal usage (CLI, config, admin tools).
 * Mirrors commonl.safe_path() behavior from Python.
 *
 * Features:
 *  - joins path components
 *  - expands ~ and environment variables
 *  - normalizes and absolutizes paths
 *  - optionally resolves symlinks
 *  - optionally enforces base_dir containment
 *  - optionally requires existence
 *
 * @param array $components   Path components to join
 * @param array $opts         Options:
 *                            - base_dir (string|null, optional)
 *                            - must_exist (bool, default false)
 *                            - resolve_symlinks (bool, default true)
 * @return string|false       Resolved safe path or false on failure
 */
function safe_path(array $components, array $opts = [])
{
    if (empty($components)) {
        return false;
    }

    // --- options ------------------------------------------------------------

    $base_dir         = $opts['base_dir'] ?? getcwd();
    $must_exist       = (bool)($opts['must_exist'] ?? false);
    $resolve_symlinks = (bool)($opts['resolve_symlinks'] ?? true);

    // --- helpers ------------------------------------------------------------

    $expand = function (string $path): string {
        // strip null bytes
        $path = str_replace("\0", '', $path);

        // expand env vars: $VAR or ${VAR}
        $path = preg_replace_callback(
            '/\$(\w+)|\$\{([^}]+)\}/',
            fn($m) => getenv($m[1] ?? $m[2]) ?: '',
            $path
        );

        // expand ~
        if ($path !== '' && $path[0] === '~') {
            $home = getenv('HOME');
            if ($home) {
                $path = $home . substr($path, 1);
            }
        }

        return $path;
    };

    $normalize = function (string $path): string {
        $parts = [];
        foreach (explode(DIRECTORY_SEPARATOR, $path) as $part) {
            if ($part === '' || $part === '.') {
                continue;
            }
            if ($part === '..') {
                array_pop($parts);
                continue;
            }
            $parts[] = $part;
        }
        return DIRECTORY_SEPARATOR . implode(DIRECTORY_SEPARATOR, $parts);
    };

    // --- expand + join ------------------------------------------------------

    $expanded = [];

    foreach ($components as $c) {
        if (!is_string($c)) {
            return false;
        }
        $expanded[] = $expand(trim($c));
    }

    $joined = implode(DIRECTORY_SEPARATOR, $expanded);

    // make absolute
    if (!str_starts_with($joined, DIRECTORY_SEPARATOR)) {
        $joined = getcwd() . DIRECTORY_SEPARATOR . $joined;
    }

    $normalized = $normalize($joined);

    // --- resolve symlinks ---------------------------------------------------

    if ($resolve_symlinks) {
        $resolved = realpath($normalized);

        // allow non-existent final target
        if ($resolved === false) {
            $parent = realpath(dirname($normalized));
            if ($parent === false) {
                return false;
            }
            $resolved = $parent . DIRECTORY_SEPARATOR . basename($normalized);
        }
    } else {
        $resolved = $normalized;
    }

    // --- optional base_dir containment -------------------------------------

    if ($base_dir !== null) {
        if (!is_string($base_dir)) {
            return false;
        }

        $base_dir = $expand($base_dir);

        if (!str_starts_with($base_dir, DIRECTORY_SEPARATOR)) {
            $base_dir = getcwd() . DIRECTORY_SEPARATOR . $base_dir;
        }

        $base_dir = $normalize($base_dir);

        if ($resolve_symlinks) {
            $base_dir = realpath($base_dir);
            if ($base_dir === false || !is_dir($base_dir)) {
                return false;
            }
        } elseif (!is_dir($base_dir)) {
            return false;
        }

        $base_dir = rtrim($base_dir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

        if (
            $resolved !== rtrim($base_dir, DIRECTORY_SEPARATOR) &&
            !str_starts_with($resolved, $base_dir)
        ) {
            return false;
        }
    }

    // --- existence check ----------------------------------------------------

    if ($must_exist && !file_exists($resolved)) {
        return false;
    }

    return $resolved;
}

/**
 * safe_path_web — secure path resolver for web-facing input
 *
 * Rules:
 *  - treats all input as untrusted
 *  - joins relative path components
 *  - forbids absolute paths
 *  - forbids ~ and env expansion
 *  - normalizes ".", ".."
 *  - enforces strict base_dir containment
 *  - optionally resolves symlinks
 *  - optionally requires existence
 *
 * @param array $components       Untrusted relative path components
 * @param array $opts             Options:
 *                                - base_dir (string, required)
 *                                - must_exist (bool, default false)
 *                                - resolve_symlinks (bool, default true)
 * @return string|false            Safe resolved path or false if invalid
 */
function safe_path_web(array $components, array $opts = [])
{
    // --- options ------------------------------------------------------------

//    if (!isset($opts['base_dir']) || !is_string($opts['base_dir'])) {
//        return false;
//    }

    if (empty($components)) {
        return false;
    }

    $base_dir         = $opts['base_dir'] ?? getcwd();
    $must_exist       = (bool)($opts['must_exist'] ?? false);
    $resolve_symlinks = (bool)($opts['resolve_symlinks'] ?? true);

    // --- base_dir validation ------------------------------------------------

    $base_dir = str_replace("\0", '', $base_dir);
    $base_dir = rtrim($base_dir, DIRECTORY_SEPARATOR);

    if (!is_dir($base_dir)) {
        return false;
    }

    $base_real = $resolve_symlinks ? realpath($base_dir) : $base_dir;
    if ($base_real === false) {
        return false;
    }

    $base_real = rtrim($base_real, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

    // --- sanitize and normalize components ----------------------------------

    $clean = [];

    foreach ($components as $c) {
        if (!is_string($c)) {
            return false;
        }

        $c = trim(str_replace("\0", '', $c));
        if ($c === '') {
            continue;
        }

        // forbid absolute paths (Unix + Windows)
        if (
            str_starts_with($c, DIRECTORY_SEPARATOR) ||
            preg_match('#^[A-Za-z]:[\\\\/]#', $c)
        ) {
            return false;
        }

        // forbid ~ and env-like expansion tokens
        if (str_contains($c, '~') || str_contains($c, '$')) {
            return false;
        }

        // split on both / and \
        $parts = preg_split('#[\\\\/]#', $c);

        foreach ($parts as $p) {
            if ($p === '' || $p === '.') {
                continue;
            }
            if ($p === '..') {
                array_pop($clean);
                continue;
            }
            $clean[] = $p;
        }
    }

    if (empty($clean)) {
        return false;
    }

    // --- construct candidate ------------------------------------------------

    $candidate = $base_real . implode(DIRECTORY_SEPARATOR, $clean);

    // --- resolve symlinks ----------------------------------------------------

    if ($resolve_symlinks) {
        $resolved = realpath($candidate);

        // allow non-existent final target (creation)
        if ($resolved === false) {
            $parent = realpath(dirname($candidate));
            if ($parent === false) {
                return false;
            }
            $resolved = $parent . DIRECTORY_SEPARATOR . basename($candidate);
        }
    } else {
        $resolved = $candidate;
    }

    // --- containment check --------------------------------------------------

    if (!str_starts_with($resolved, $base_real)) {
        return false;
    }

    // --- existence check ----------------------------------------------------

    if ($must_exist && !file_exists($resolved)) {
        return false;
    }

    return $resolved;
}

/**
 * Append paths to the PHP include_path if they are not already present.
 *
 * @param array $paths  Array of directory paths to add.
 * @return void
 * @since 20251223
 */
function add_include_paths(array $paths): void
{
    $separator = PATH_SEPARATOR;

    // Current include_path entries
    $current = array_filter(
        explode($separator, get_include_path()),
        'strlen'
    );

    // Normalize existing paths
    $current = array_map(
        static fn($p) => rtrim($p, DIRECTORY_SEPARATOR),
        $current
    );

    foreach ($paths as $path) {
        if (!is_string($path) || $path === '') {
            continue;
        }

        $normalized = rtrim($path, DIRECTORY_SEPARATOR);

        if (!in_array($normalized, $current, true)) {
            $current[] = $normalized;
        }
    }

    set_include_path(implode($separator, $current));
}

} /* namespace bbsengine6\util */

?>
