<?php

namespace bbsengine6\util
{
    /**
     * put $message into a log at the given priority
     *
     * @since 20080105
     * @since 20221116
     * @param string
     * @param enum
     */
    function logentry(string $message, int $priority=\PEAR_LOG_DEBUG)
    {

      if (defined("LOGENTRYPREFIX") === false)
      {
        define("LOGENTRYPREFIX", "bbsengine6");
      }

      $logger = \Log::factory("syslog", "", LOGENTRYPREFIX, [], \PEAR_LOG_DEBUG);
    //  $logger->log("bbsengine5.logentry.100: _SERVER=".var_export($_SERVER, true), $priority);
      $ip = getremoteaddr(); // $_SERVER["REMOTE_ADDR"];

      $logger->log($message, $priority);
      return;
    }

    /**
     * calls json_encode() with default parameters
     *
     * @since 20140730
     * @since 20230329 copied from bbsengine5.php
     */
    function encodejson($data)
    {
     // @see http://us3.php.net/manual/en/json.constants.php
     return json_encode($data); // , JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_NUMERIC_CHECK); // JSON_UNESCAPED_UNICODE in 5.4+
    }

    /**
     * decodes given json data into a dictionary (associative array)
     *
     * @since 20140730
     * @since 20230329 copied from bbsengine5.php
     */
    function decodejson($data)
    {
     if (is_string($data) === false)
     {
      logentry("decodejson.100: data=".var_export($data, true));
      return;
     }
     return json_decode($data, true);
    }

    /**
     * @since 20180804
     * @since 20240807 ported to bbsengine6
     * @since 20240914 moved to \bbsengine6\util
     * @param mixed field
     * @param string label
     * @param boolean default
     * @return boolean
     */
    function toboolean($value, $label="label", $default=false)
    {
      if (is_null($value) === true)
      {
        return $default;
      }

      if (is_bool($value) === true)
      {
        return $value;
      }

      if ($value === "t" || $value == 1 || $value == "true")
      {
        return true;
      }

      if ($value === "f" || $value == 0 || $value == "false")
      {
        return false;
      }

    //  logentry("toboolean.170: returning default of ".var_export($default, true)." for ".var_export($label, true));
      return $default;
    }

  // @since 20240921 generated by chatgpt.com
  function ltreeToPath(string $ltree) {
    // Split the ltree path by periods
    $labels = explode('.', $ltree);

    // Remove the reference to 'top'
    if ($labels[0] === 'top') {
      array_shift($labels);
    }

    // Join the remaining labels into a filesystem path with slashes
    return implode('/', $labels);
  }

  // @since 20250619
  // Converts a URI path to a valid ltree path. Replaces "/" with "." and "-" with "_".
  // Example: "software/python" -> "software.python", "ec_john-edward" -> "ec_john_edward"
  function pathToLtree(string $path): string {
    return str_replace("-", "_", str_replace("/", ".", $path));
  }

  // @since 20240921 generated by chatgpt.com
  function chopLastElement($ltree) {
    $labels = explode('.', $ltree);
    logentry("engine.util.chopLastElement.100: ltree=".var_export($ltree, true)." labels=".var_export($labels, true));
/*
    // If there's only one element, return the original ltree
    if (count($labels) <= 1) {
        return $ltree;
    }
*/
    array_pop($labels);
    return implode('.', $labels);
  }

  // @since 20241030
  // @since 20251128 security: added IP validation to prevent spoofing
  function getremoteaddr(bool $allowForwarded = false): ?string
  {
    $result = null;

    if ($allowForwarded)
    {
      if (!empty($_SERVER['HTTP_CLIENT_IP']))
      {
        $result = trim($_SERVER['HTTP_CLIENT_IP']);
      }
      elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR']))
      {
        $ipList = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);
        $result = trim($ipList[0]);
      }
    }

    if ($result === null)
    {
      $result = $_SERVER["REMOTE_ADDR"] ?? null;
    }

    if ($result !== null && filter_var($result, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) === false)
    {
      $result = $_SERVER["REMOTE_ADDR"] ?? null;
    }

    return $result;
  }

  function getremoteaddr_allowforwarded(): ?string
  {
    return getremoteaddr(true);
  }

  function actionlog(string $action, string $note=null, string $moniker=null)
  {
    if ($moniker === null)
    {
      $moniker = \bbsengine6\member\lib\getcurrentmoniker();
    }
    $pdo = \bbsengine6\database\connect(\config\SYSTEMDSN);
    $data = ["moniker" => $moniker, "action" => $action, "actiondate" => "now()","remoteaddr" => getremoteaddr(), "note" => $note];
    \bbsengine6\database\insert($pdo, "engine.__actionlog", $data, $returnid=false, $mogrify=true);

    return true;
  }

  const CSRF_TOKEN_NAME = 'csrf_token';
  const CSRF_TOKEN_LENGTH = 32;

  function csrfGenerateToken(): string
  {
    if (session_status() === PHP_SESSION_NONE)
    {
      session_start();
    }

    if (!isset($_SESSION[CSRF_TOKEN_NAME]))
    {
      $_SESSION[CSRF_TOKEN_NAME] = bin2hex(random_bytes(CSRF_TOKEN_LENGTH));
    }

    return $_SESSION[CSRF_TOKEN_NAME];
  }

  function csrfGetToken(): string
  {
    return csrfGenerateToken();
  }

  function csrfValidateToken(string $token): bool
  {
    if (session_status() === PHP_SESSION_NONE)
    {
      session_start();
    }

    if (!isset($_SESSION[CSRF_TOKEN_NAME]))
    {
      return false;
    }

    $storedToken = $_SESSION[CSRF_TOKEN_NAME];
    return hash_equals($storedToken, $token);
  }

  function csrfTokenField(): string
  {
    $token = csrfGetToken();
    return '<input type="hidden" name="' . CSRF_TOKEN_NAME . '" value="' . htmlspecialchars($token, ENT_QUOTES, 'UTF-8') . '">';
  }

  function csrfCheckRequest(bool $requireOnGet = false): bool
  {
    if ($_SERVER['REQUEST_METHOD'] === 'POST')
    {
      $token = $_POST[CSRF_TOKEN_NAME] ?? $_POST['csrf_token'] ?? null;
      if ($token === null)
      {
        logentry("csrfCheckRequest.100: missing token in POST");
        return false;
      }
      return csrfValidateToken($token);
    }
    elseif ($_SERVER['REQUEST_METHOD'] === 'GET')
    {
      $token = $_GET[CSRF_TOKEN_NAME] ?? $_GET['csrf_token'] ?? null;
      if ($token === null)
      {
        if ($requireOnGet === true)
        {
          logentry("csrfCheckRequest.110: missing token in GET when required");
          return false;
        }
        return true;
      }
      return csrfValidateToken($token);
    }
    return true;
  }

  function isDebugMode(): bool
  {
    return getenv('DEBUG') === '1' || ($_SERVER['DEBUG'] ?? '0') === '1';
  }

  function format_exception(\Throwable $e): string
  {
    $trace = $e->getTraceAsString();
    $prev = $e->getPrevious();
    while ($prev !== null) {
      $trace .= "\n\nPrevious: " . $prev->getMessage() . "\n" . $prev->getTraceAsString();
      $prev = $prev->getPrevious();
    }
    return $e->getMessage() . "\n" . $trace;
  }

  function echo_traceback(string $message, bool $showToUser = null): void
  {
    if ($showToUser === null) {
      $showToUser = isDebugMode();
    }

    $e = error_get_last();
    $formatted = '';
    if ($e !== null) {
      $formatted = $e['message'] . " in " . $e['file'] . " line " . $e['line'];
    }

    logentry("ERROR: " . $message . " | Trace: " . $formatted);

    if ($showToUser) {
      echo "<pre style='background:#fee;border:1px solid red;padding:10px;'>Error: " . htmlspecialchars($message, ENT_QUOTES, 'UTF-8') . "\n" . htmlspecialchars($formatted, ENT_QUOTES, 'UTF-8') . "</pre>";
    } else {
      $safe = preg_replace('/SQLSTATE\[[A-Z0-9]+\]:[^\n]*/', 'SQLSTATE[xxxxx]: [details suppressed]', $message);
      $safe = preg_replace('/PDOException[^\n]*/', '[PDOException suppressed]', $safe);
      echo "Error: " . htmlspecialchars($safe, ENT_QUOTES, 'UTF-8');
    }
  }

/**
 * safe_path — robust, flexible filesystem path constructor
 *
 * Intended for trusted/internal usage (CLI, config, admin tools).
 * Mirrors commonl.safe_path() behavior from Python.
 *
 * Features:
 *  - joins path components
 *  - expands ~ and environment variables
 *  - normalizes and absolutizes paths
 *  - optionally resolves symlinks
 *  - optionally enforces base_dir containment
 *  - optionally requires existence
 *
 * @param array $components   Path components to join
 * @param array $opts         Options:
 *                            - base_dir (string|null, optional)
 *                            - must_exist (bool, default false)
 *                            - resolve_symlinks (bool, default true)
 * @return string|false       Resolved safe path or false on failure
 */
function safe_path(array $components, array $opts = [])
{
    if (empty($components)) {
        return false;
    }

    // --- options ------------------------------------------------------------

    $base_dir         = $opts['base_dir'] ?? getcwd();
    $must_exist       = (bool)($opts['must_exist'] ?? false);
    $resolve_symlinks = (bool)($opts['resolve_symlinks'] ?? true);

    // --- helpers ------------------------------------------------------------

    $expand = function (string $path): string {
        // strip null bytes
        $path = str_replace("\0", '', $path);

        // expand env vars: $VAR or ${VAR}
        $path = preg_replace_callback(
            '/\$(\w+)|\$\{([^}]+)\}/',
            fn($m) => getenv($m[1] ?? $m[2]) ?: '',
            $path
        );

        // expand ~
        if ($path !== '' && $path[0] === '~') {
            $home = getenv('HOME');
            if ($home) {
                $path = $home . substr($path, 1);
            }
        }

        return $path;
    };

    $normalize = function (string $path): string {
        $parts = [];
        foreach (explode(DIRECTORY_SEPARATOR, $path) as $part) {
            if ($part === '' || $part === '.') {
                continue;
            }
            if ($part === '..') {
                array_pop($parts);
                continue;
            }
            $parts[] = $part;
        }
        return DIRECTORY_SEPARATOR . implode(DIRECTORY_SEPARATOR, $parts);
    };

    // --- expand + join ------------------------------------------------------

    $expanded = [];

    foreach ($components as $c) {
        if (!is_string($c)) {
            return false;
        }
        $expanded[] = $expand(trim($c));
    }

    $joined = implode(DIRECTORY_SEPARATOR, $expanded);

    // make absolute
    if (!str_starts_with($joined, DIRECTORY_SEPARATOR)) {
        $joined = getcwd() . DIRECTORY_SEPARATOR . $joined;
    }

    $normalized = $normalize($joined);

    // --- resolve symlinks ---------------------------------------------------

    if ($resolve_symlinks) {
        $resolved = realpath($normalized);

        // allow non-existent final target
        if ($resolved === false) {
            $parent = realpath(dirname($normalized));
            if ($parent === false) {
                return false;
            }
            $resolved = $parent . DIRECTORY_SEPARATOR . basename($normalized);
        }
    } else {
        $resolved = $normalized;
    }

    // --- optional base_dir containment -------------------------------------

    if ($base_dir !== null) {
        if (!is_string($base_dir)) {
            return false;
        }

        $base_dir = $expand($base_dir);

        if (!str_starts_with($base_dir, DIRECTORY_SEPARATOR)) {
            $base_dir = getcwd() . DIRECTORY_SEPARATOR . $base_dir;
        }

        $base_dir = $normalize($base_dir);

        if ($resolve_symlinks) {
            $base_dir = realpath($base_dir);
            if ($base_dir === false || !is_dir($base_dir)) {
                return false;
            }
        } elseif (!is_dir($base_dir)) {
            return false;
        }

        $base_dir = rtrim($base_dir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

        if (
            $resolved !== rtrim($base_dir, DIRECTORY_SEPARATOR) &&
            !str_starts_with($resolved, $base_dir)
        ) {
            return false;
        }
    }

    // --- existence check ----------------------------------------------------

    if ($must_exist && !file_exists($resolved)) {
        return false;
    }

    return $resolved;
}

/**
 * safe_path_web — secure path resolver for web-facing input
 *
 * Rules:
 *  - treats all input as untrusted
 *  - joins relative path components
 *  - forbids absolute paths
 *  - forbids ~ and env expansion
 *  - normalizes ".", ".."
 *  - enforces strict base_dir containment
 *  - optionally resolves symlinks
 *  - optionally requires existence
 *
 * @param array $components       Untrusted relative path components
 * @param array $opts             Options:
 *                                - base_dir (string, required)
 *                                - must_exist (bool, default false)
 *                                - resolve_symlinks (bool, default true)
 * @return string|false            Safe resolved path or false if invalid
 */
function safe_path_web(array $components, array $opts = [])
{
    // --- options ------------------------------------------------------------

//    if (!isset($opts['base_dir']) || !is_string($opts['base_dir'])) {
//        return false;
//    }

    if (empty($components)) {
        return false;
    }

    $base_dir         = $opts['base_dir'] ?? getcwd();
    $must_exist       = (bool)($opts['must_exist'] ?? false);
    $resolve_symlinks = (bool)($opts['resolve_symlinks'] ?? true);

    // --- base_dir validation ------------------------------------------------

    $base_dir = str_replace("\0", '', $base_dir);
    $base_dir = rtrim($base_dir, DIRECTORY_SEPARATOR);

    if (!is_dir($base_dir)) {
        return false;
    }

    $base_real = $resolve_symlinks ? realpath($base_dir) : $base_dir;
    if ($base_real === false) {
        return false;
    }

    $base_real = rtrim($base_real, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

    // --- sanitize and normalize components ----------------------------------

    $clean = [];

    foreach ($components as $c) {
        if (!is_string($c)) {
            return false;
        }

        $c = trim(str_replace("\0", '', $c));
        if ($c === '') {
            continue;
        }

        // forbid absolute paths (Unix + Windows)
        if (
            str_starts_with($c, DIRECTORY_SEPARATOR) ||
            preg_match('#^[A-Za-z]:[\\\\/]#', $c)
        ) {
            return false;
        }

        // forbid ~ and env-like expansion tokens
        if (str_contains($c, '~') || str_contains($c, '$')) {
            return false;
        }

        // split on both / and \
        $parts = preg_split('#[\\\\/]#', $c);

        foreach ($parts as $p) {
            if ($p === '' || $p === '.') {
                continue;
            }
            if ($p === '..') {
                array_pop($clean);
                continue;
            }
            $clean[] = $p;
        }
    }

    if (empty($clean)) {
        return false;
    }

    // --- construct candidate ------------------------------------------------

    $candidate = $base_real . implode(DIRECTORY_SEPARATOR, $clean);

    // --- resolve symlinks ----------------------------------------------------

    if ($resolve_symlinks) {
        $resolved = realpath($candidate);

        // allow non-existent final target (creation)
        if ($resolved === false) {
            $parent = realpath(dirname($candidate));
            if ($parent === false) {
                return false;
            }
            $resolved = $parent . DIRECTORY_SEPARATOR . basename($candidate);
        }
    } else {
        $resolved = $candidate;
    }

    // --- containment check --------------------------------------------------

    if (!str_starts_with($resolved, $base_real)) {
        return false;
    }

    // --- existence check ----------------------------------------------------

    if ($must_exist && !file_exists($resolved)) {
        return false;
    }

    return $resolved;
}

/**
   * Recursively redact secret-looking values from an array so it is safe
   * to pass through var_export / logentry / error_log.
   *
   * Replaces any key matching /password|passwd|repeat|secret|token|api[_-]?key|credential|hash/i
   * with the string '***'. Walks nested arrays; leaves non-array scalars untouched.
   *
   * @param mixed $value
   * @return mixed
   * @since 20260802
   */
  function redact_secrets($value)
  {
    if (!is_array($value)) {
      return $value;
    }

    $pattern = '/(password|passwd|repeat|secret|token|api[_-]?key|credential|hash)/i';
    $out = [];
    foreach ($value as $k => $v) {
      if (is_string($k) && preg_match($pattern, $k) === 1) {
        $out[$k] = '***';
      } elseif (is_array($v)) {
        $out[$k] = redact_secrets($v);
      } else {
        $out[$k] = $v;
      }
    }
    return $out;
  }

  /**
   * Append paths to the PHP include_path if they are not already present.
   *
   * @param array $paths  Array of directory paths to add.
   * @return void
   * @since 20251223
   */
  function add_include_paths(array $paths): void
{
    $separator = PATH_SEPARATOR;

    // Current include_path entries
    $current = array_filter(
        explode($separator, get_include_path()),
        'strlen'
    );

    // Normalize existing paths
    $current = array_map(
        static fn($p) => rtrim($p, DIRECTORY_SEPARATOR),
        $current
    );

    foreach ($paths as $path) {
        if (!is_string($path) || $path === '') {
            continue;
        }

        $normalized = rtrim($path, DIRECTORY_SEPARATOR);

        if (!in_array($normalized, $current, true)) {
            $current[] = $normalized;
        }
    }

    set_include_path(implode($separator, $current));
}

    /**
     * canonical filesystem root for the bbsengine.org handbook tree
     *
     * Resolution order:
     *   1. getenv('BBSENGINE6_HANDBOOK_HOME') -- lets htaccess/apache
     *      or a test harness override the location without editing
     *      this file.
     *   2. defined('BBSENGINE6_HANDBOOK_HOME') -- a PHP-side override
     *      (e.g. set in config.php).
     *   3. The canonical install path on the bbsengine.org vhost:
     *      /srv/www/vhosts/www.bbsengine.org/html/handbook/.
     *      This is the same path engine/router.php:569 hardcoded
     *      before this helper existed.
     *
     * @since 2026-09-09
     * @return string absolute filesystem path, with trailing slash
     */
    function handbook_home(): string
    {
        $env = getenv('BBSENGINE6_HANDBOOK_HOME');
        if (is_string($env) && $env !== '') {
            return rtrim($env, '/') . '/';
        }
        if (defined('BBSENGINE6_HANDBOOK_HOME')) {
            $c = constant('BBSENGINE6_HANDBOOK_HOME');
            if (is_string($c) && $c !== '') {
                return rtrim($c, '/') . '/';
            }
        }
        return '/srv/www/vhosts/www.bbsengine.org/html/handbook/';
    }

    /**
     * resolve a handbook-relative (prefix, path) pair to an absolute
     * filesystem path, with traversal and extension safety checks.
     *
     * Contract:
     *   $prefix is the handbook subdirectory (e.g. 'handbook/6'),
     *   as emitted by the htaccess-prod rule for /handbook/<v>/<uri>.md
     *   (see www/org/htaccess-prod:55).
     *   $path is the file under that prefix (e.g. 'specs/auth-bank.md').
     *   The resolved file must:
     *     - exist as a regular file,
     *     - have a .md extension,
     *     - lie under handbook_home() (defense against path
     *       traversal in either argument).
     *
     * @since 2026-09-09
     * @param string $prefix handbook subdirectory (e.g. 'handbook/6')
     * @param string $path   file relative to prefix (e.g. 'specs/auth-bank.md')
     * @return string|false  absolute path on success, false on any
     *                       failure (missing args, traversal, missing
     *                       file, wrong extension).
     */
    function handbook_resolve(string $prefix, string $path)
    {
        if ($prefix === '' || $path === '') {
            return false;
        }
        // Normalize: the htaccess-prod rule emits prefix=handbook/<v>
        // (because the URL path is /handbook/<v>/<uri>.md), but
        // handbook_home() already ends in /handbook/. Strip a
        // leading 'handbook/' from the prefix so callers can pass
        // either shape (prefix='6' or prefix='handbook/6') without
        // having to know about handbook_home()'s tail.
        if (strpos($prefix, 'handbook/') === 0) {
            $prefix = substr($prefix, strlen('handbook/'));
        }
        if ($prefix === '') {
            return false;
        }
        $home = handbook_home();
        $baseRaw = $home . $prefix;
        $base = realpath($baseRaw);
        if ($base === false) {
            return false;
        }
        $homeReal = realpath($home);
        if ($homeReal === false) {
            return false;
        }
        $homeReal = rtrim($homeReal, '/') . '/';
        $base = rtrim($base, '/') . '/';
        // prefix must be a descendant of handbook_home()
        if (strpos($base, $homeReal) !== 0) {
            return false;
        }
        $file = realpath($base . $path);
        if ($file === false) {
            return false;
        }
        // file must be a descendant of $base
        if (strpos($file, $base) !== 0) {
            return false;
        }
        if (!is_file($file)) {
            return false;
        }
        if (pathinfo($file, PATHINFO_EXTENSION) !== 'md') {
            return false;
        }
        return $file;
    }

    /**
     * canonical catalog content root (the "catalog" is the teos
     * content tree: rec/, ec/, comp/, alt/, sci/, usgov/, etc.)
     *
     * Sibling of handbook_home() (which returns the handbook
     * tree root) and teos_dir() (which returns the same value
     * via the TEOSDIR env/constant/default chain). Exists so
     * callers that semantically want "the catalog root, not the
     * teos docroot" can read it without the TEOSDIR indirection
     * -- in particular, the /engine/router.php HTTP entry point
     * and the bbsengine6\blurb\* helpers that render
     * /rec/arts/... (catalog) pages, which used to read TEOSDIR
     * directly and 500'd on the live vhost when TEOSDIR was
     * misconfigured or pointed at a non-catalog tree.
     *
     * Resolution order:
     *   1. getenv('CATALOG_ROOT') -- test-harness or operator
     *      override.
     *   2. defined('CATALOG_ROOT') -- PHP-side override (e.g.
     *      set in config.php).
     *   3. defined('TEOSDIR') -- the legacy teos-catalog constant
     *      (preserved so existing config.php files keep working
     *      without modification).
     *   4. Hardcoded default: the teos docroot.
     *
     * @since 2026-09-10
     * @return string absolute filesystem path, with trailing slash
     */
    function catalog_root(): string
    {
        $env = getenv('CATALOG_ROOT');
        if (is_string($env) && $env !== '') {
            return rtrim($env, '/') . '/';
        }
        if (defined('CATALOG_ROOT')) {
            $c = constant('CATALOG_ROOT');
            if (is_string($c) && $c !== '') {
                return rtrim($c, '/') . '/';
            }
        }
        // Fall back to TEOSDIR (env first, then constant) for
        // backward compat with existing vhost configs that only
        // set TEOSDIR. The handbook/6 router entry point putenv()s
        // TEOSDIR for the handbook tree, so any caller reaching
        // here from /handbook/<v>/... should still see the
        // handbook path.
        $env = getenv('TEOSDIR');
        if (is_string($env) && $env !== '') {
            return rtrim($env, '/') . '/';
        }
        if (defined('TEOSDIR')) {
            $c = constant('TEOSDIR');
            if (is_string($c) && $c !== '') {
                return rtrim($c, '/') . '/';
            }
        }
        return '/srv/www/vhosts/zoidtechnologies.com/html/teos/';
    }

    /**
     * canonical vhost-polymorphic content root
     *
     * TEOSDIR is intentionally polymorphic: router.php:577-585
     * putenv()s it to the handbook tree root (/srv/www/vhosts/
     * www.bbsengine.org/html/handbook/<v>/) for /handbook/<v>/
     * requests, and leaves it at the teos docroot for /teos/
     * requests. Callers that read files (blurb.php, folder.php,
     * engine.php) used to repeat `defined('TEOSDIR') ? TEOSDIR :
     * '/srv/.../zoid...'`. This helper centralizes that pattern.
     *
     * @since 2026-09-09
     * @return string absolute filesystem path, with trailing slash
     */
    function teos_dir(): string
    {
        // @since 2026-09-10 — delegate to catalog_root() so the
        // catalog and the teos-dir helpers stay in lockstep when
        // a CATALOG_ROOT override is set (the catalog is the
        // teos content tree; they're the same path, just
        // different framings of "where do rec/, ec/, comp/, etc.
        // live"). Callers that want the vhost-agnostic
        // handbook-vs-catalog split should call
        // bbsengine6\util\handbook_home() or
        // bbsengine6\util\catalog_root() directly.
        return catalog_root();
    }

    /**
     * canonical vhost-polymorphic content URL prefix
     *
     * Mirror of teos_dir() for the URL prefix (TEOSURL). router.php
     * putenv()s TEOSURL to '/handbook/<v>/' for handbook requests
     * and '/teos/' for teos requests. engine.php's bare \TEOSURL
     * callers used to read the constant directly, returning an
     * empty string with a PHP notice if undefined.
     *
     * The default is '' (matching the bare-constant behavior) so
     * that callers which previously relied on \TEOSURL returning
     * empty string when not configured continue to behave the same
     * way. Callers that need a real prefix should read it from the
     * per-vhost config.
     *
     * @since 2026-09-09
     * @return string URL prefix (e.g. '/handbook/6/' or '/teos/')
     */
    function teos_url(): string
    {
        $env = getenv('TEOSURL');
        if (is_string($env) && $env !== '') {
            return $env;
        }
        if (defined('TEOSURL')) {
            $c = constant('TEOSURL');
            if (is_string($c) && $c !== '') {
                return $c;
            }
        }
        return '';
    }

    /**
     * per-vhost display label for the top-level "root" breadcrumb
     *
     * Used by both router_buildBreadcrumbs (engine/router.php)
     * and bbsengine6\blurb\buildbreadcrumbs (php/blurb.php) to
     * keep the DB-driven and filesystem-driven breadcrumb paths
     * in lockstep. Default is "teos" so existing /teos/ callers
     * (and any environment that neither defines nor exports the
     * constant) see no change. The bbsengine.org /handbook/<v>/
     * dispatch block in engine/router.php putenv()s
     * TEOS_LABEL="bbsengine6 handbook" for handbook requests,
     * mirroring the pattern used for TEOSDIR/TEOSURL and the
     * original export in the (now-deleted) www/org/php/handbook.php
     * (commit c40c79a).
     *
     * Promoted from bbsengine6\blurb\getlabel (php/blurb.php)
     * to util so that callers outside the blurb namespace
     * (specifically router_buildBreadcrumbs) can read the
     * label without pulling in the blurb.php require chain
     * (zoid6\bootstrap, zoid6config.php, zoid6.php, ...). The
     * blurb.php function still exists for backward compat and
     * delegates to this helper.
     *
     * @since 2026-09-10
     * @return string The label to render for the top breadcrumb.
     */
    function vhost_label(): string
    {
        $env = getenv('TEOS_LABEL');
        if (is_string($env) && $env !== '') {
            return $env;
        }
        if (defined('TEOS_LABEL')) {
            $c = constant('TEOS_LABEL');
            if (is_string($c) && $c !== '') {
                return $c;
            }
        }
        return 'teos';
    }

} /* namespace bbsengine6\util */

?>
