<?php

namespace bbsengine6\util
{
    /**
     * put $message into a log at the given priority
     *
     * @since 20080105
     * @since 20221116
     * @param string
     * @param enum
     */
    function logentry(string $message, int $priority=PEAR_LOG_DEBUG)
    {

      if (defined("LOGENTRYPREFIX") === false)
      {
        define("LOGENTRYPREFIX", "bbsengine6");
      }

      $logger = \Log::factory("syslog", "", LOGENTRYPREFIX, [], PEAR_LOG_DEBUG);
    //  $logger->log("bbsengine5.logentry.100: _SERVER=".var_export($_SERVER, true), $priority);
      $ip = getremoteaddr(); // $_SERVER["REMOTE_ADDR"];

      $logger->log($message, $priority);
      return;
    }

    /**
     * calls json_encode() with default parameters
     *
     * @since 20140730
     * @since 20230329 copied from bbsengine5.php
     */
    function encodejson($data)
    {
     // @see http://us3.php.net/manual/en/json.constants.php
     return json_encode($data); // , JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_NUMERIC_CHECK); // JSON_UNESCAPED_UNICODE in 5.4+
    }

    /**
     * decodes given json data into a dictionary (associative array)
     *
     * @since 20140730
     * @since 20230329 copied from bbsengine5.php
     */
    function decodejson($data)
    {
     if (is_string($data) === false)
     {
      logentry("decodejson.100: data=".var_export($data, true));
      return;
     }
     return json_decode($data, true);
    }

    /**
     * @since 20180804
     * @since 20240807 ported to bbsengine6
     * @since 20240914 moved to \bbsengine6\util
     * @param mixed field
     * @param string label
     * @param boolean default
     * @return boolean
     */
    function toboolean($value, $label="label", $default=false)
    {
      if (is_null($value) === true)
      {
        return $default;
      }

      if (is_bool($value) === true)
      {
        return $value;
      }

      if ($value === "t" || $value == 1 || $value == "true")
      {
        return true;
      }

      if ($value === "f" || $value == 0 || $value == "false")
      {
        return false;
      }

    //  logentry("toboolean.170: returning default of ".var_export($default, true)." for ".var_export($label, true));
      return $default;
    }

  // @since 20240921 generated by chatgpt.com
  function ltreeToPath(string $ltree) {
    // Split the ltree path by periods
    $labels = explode('.', $ltree);

    // Remove the reference to 'top'
    if ($labels[0] === 'top') {
      array_shift($labels);
    }

    // Join the remaining labels into a filesystem path with slashes
    return implode('/', $labels);
  }

  // @since 20240921 generated by chatgpt.com
  function chopLastElement($ltree) {
    $labels = explode('.', $ltree);
    logentry("engine.util.chopLastElement.100: ltree=".var_export($ltree, true)." labels=".var_export($labels, true));
/*
    // If there's only one element, return the original ltree
    if (count($labels) <= 1) {
        return $ltree;
    }
*/
    array_pop($labels);
    return implode('.', $labels);
  }

  // @since 20241030
  function getremoteaddr()
  {
    $result = "";
    if (!empty($_SERVER['HTTP_CLIENT_IP']))
    {
      $result = $_SERVER['HTTP_CLIENT_IP'];
    }
    elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR']))
    {
      // Handle multiple forwarded IPs
      $ipList = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);
      $result = trim($ipList[0]);
    }
    else
    {
      $result = $_SERVER["REMOTE_ADDR"];
    }

    return $result;

/*
    if (filter_var($result, FILTER_VALIDATE_IP) === true)
    {
      return $result;
    }
*/
    return null;
  }

  function actionlog(string $action, string $note=null, string $moniker=null)
  {
    if ($moniker === null)
    {
      $moniker = \bbsengine6\member\lib\getcurrentmoniker();
    }
    $pdo = \bbsengine6\database\connect(\config\SYSTEMDSN);
    $data = ["moniker" => $moniker, "action" => $action, "actiondate" => "now()","remoteaddr" => getremoteaddr(), "note" => $note];
    \bbsengine6\database\insert($pdo, "engine.__actionlog", $data, $returnid=false, $mogrify=true);

    return true;
  }

}

?>
