\i plpythonu.sql
\i extensions.sql
\i roles.sql
\i schema.sql
\i buildsiguri.sql
\i member.sql
\i session.sql
\i notify.sql
\i sig.sql
\i flag.sql
\i flagdata.sql
\i tag.sql
\i node.sql
\i tagmap.sql
\i nodeview.sql
\i mantra.sql
\i memberview.sql
\i memberinet.sql
\i subscribe.sql
