-- generated by chatgpt.com 20241101

CREATE OR REPLACE FUNCTION engine.checkflag(flag_name TEXT, moniker TEXT DEFAULT NULL)
RETURNS BOOLEAN AS $$
DECLARE
    map_value BOOLEAN;
    default_value BOOLEAN;
BEGIN
    flag_name := UPPER(flag_name);
    IF moniker IS NOT NULL THEN
        moniker := LOWER(moniker);
    END IF;
--    moniker := UPPER(moniker);

    -- Check if flag_name exists in the flag table
    PERFORM 1 FROM engine.flag WHERE name = flag_name;
    
    -- If flag_name does not exist, return NULL
    IF NOT FOUND THEN
        raise notice 'flag_name not found %', flag_name;
        RETURN NULL;
    END IF;

    -- Check if a moniker was provided and look for a matching entry in the member table
    IF moniker IS NOT NULL THEN
        PERFORM 1 FROM engine.member WHERE LOWER(engine.member.moniker) = checkflag.moniker;
        
        -- If moniker does not exist in the member table, return NULL
        IF NOT FOUND THEN
            RAISE NOTICE 'moniker not found in member table: %', moniker;
            RETURN NULL;
        END IF;

        -- Look for a matching entry in the map table
        SELECT COALESCE(m.value, (SELECT f.defaultvalue FROM engine.flag f WHERE f.name = flag_name))
        INTO map_value
        FROM engine.map_member_flag m
        WHERE LOWER(m.moniker) = checkflag.moniker AND m.name = flag_name;

        -- If a value is found in the map, return it
        IF map_value is not null THEN
            RETURN map_value;  -- Return the BOOLEAN directly from the map
        END IF;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
