-- generated by chatgpt.com 2024-10-14
CREATE OR REPLACE FUNCTION engine.createrol(role_name TEXT) 
RETURNS BOOLEAN AS 
$$
DECLARE
    sql TEXT;
BEGIN
    -- Construct the SQL query to create the role
    sql := format('CREATE ROLE %I', role_name);
    
    -- Execute the constructed SQL query
    EXECUTE sql;
    
    -- Return true to indicate success
    RETURN TRUE;
EXCEPTION
    WHEN OTHERS THEN
        -- Handle any exceptions by raising the error
        RAISE EXCEPTION 'Error creating role: %', SQLERRM;
        RETURN FALSE;
END;
$$
LANGUAGE plpgsql;

grant execute on function engine.createrol to sysop;
